
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: ApiDb
    ports:
      - "3306:3306"
    volumes:
       - ./database/script_inicial.sql:/docker-entrypoint-initdb.d/script_inicial.sql  # Mapeia seu script inicial para o contêiner
    networks:
      - api_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # Mapeia a porta 5000 da sua máquina para a porta padrão interna do container
    depends_on:
      db:
        condition: service_healthy # Garante que a API só liga quando o script do MySQL terminar
    environment:
      - ConnectionStrings__MySqlDbConnection=server=db;port=3306;userid=root;password=123456;database=ApiDb;persistsecurityinfo=True;
      - ASPNETCORE_ENVIRONMENT=Development
    networks: 
      - api_network


volumes:
  mysql_data:

networks:
  api_network:
    driver: bridge
